name: on-push
on: [push, pull_request]
env:
  MIX_ENV: test
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        otp: ["24"]
        elixir: ["1.11", "1.12", "1.13", "1.14", "1.15"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
          version-type: strict
      - uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: "*"
      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
        if: matrix.elixir == '1.15' # Only check formatting with the latest verison
      - run: mix dialyzer
        if: matrix.elixir == '1.15'
      - run: mix test
